# CE49X: Introduction to Computational Thinking and Data Science for Civil Engineers
## Week 3a: NumPy - Numerical Computing for Engineers

**Instructor:** Dr. Eyuphan Koc  
**Department of Civil Engineering, Bogazici University**  
**Semester:** Spring 2026

---

Based on "Python Data Science Handbook" by Jake VanderPlas  
Chapter 2: Introduction to NumPy  
https://github.com/jakevdp/PythonDataScienceHandbook

### Topics Covered (Sections 1-9):
1. Introduction to NumPy
2. Array Fundamentals
3. Array Operations & Ufuncs
4. Aggregations & Statistics
5. Broadcasting
6. Boolean Operations
7. Advanced Indexing
8. Sorting
9. Structured Data

In [ ]:
# Setup: Import required libraries
import numpy as np
import time
import matplotlib.pyplot as plt

print(f"NumPy version: {np.__version__}")

---
## 1. Introduction to NumPy

### What is NumPy?

> **NumPy = Numerical Python**
> - Fundamental package for scientific computing in Python
> - Provides fast, efficient multi-dimensional arrays
> - Foundation for Pandas, SciPy, Matplotlib, and more
> - Written in C - blazing fast performance

> **Example: Why NumPy?**
> - Efficient operations on large datasets
> - Vectorized computations (no loops!)
> - Broadcasting for operations on different shapes
> - Essential for data science and scientific computing
> - Foundation for the entire PyData ecosystem

### [TOGETHER] Speed Comparison: Lists vs NumPy

| Python Lists | NumPy Arrays |
|---|---|
| Flexible but slow | Fixed type - no checking |
| Type checking at every operation | Contiguous memory block |
| Overhead for each element | Vectorized C operations |

In [ ]:
# Python list: slow
import time
L = list(range(1000000))
start = time.time()
result = [x**2 for x in L]
print(f"Time: {time.time()-start:.4f}s")
# Time: ~0.15s

In [ ]:
# NumPy array: fast!
import numpy as np
A = np.arange(1000000)
start = time.time()
result = A**2
print(f"Time: {time.time()-start:.4f}s")
# Time: ~0.002s  (75x faster!)

> **Key Insight: Key Takeaway**
> NumPy is 10-100x faster for numerical operations! Essential for large engineering datasets.

### Installing and Importing NumPy

In [ ]:
import numpy as np  # ALWAYS use this convention!

# Check version
print(np.__version__)  # e.g., '1.24.3'

> **Example: Why `np`?**
> Universal convention in data science community - makes code readable to everyone

### Creating Your First NumPy Arrays

In [ ]:
import numpy as np

# From Python list - 1D array
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)  # [1 2 3 4 5]

# 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Unlike lists, all elements must be same type!
mixed = np.array([1, 2.5, 3])  # Will convert to float
print(mixed.dtype)  # dtype('float64')

---
## 2. Array Fundamentals

### Creating Arrays: Common Methods

In [ ]:
import numpy as np

# Zeros - initialize array
zeros = np.zeros(10)  # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeros_matrix = np.zeros((3, 3))  # 3x3 matrix of zeros

# Ones
ones = np.ones(5)  # [1. 1. 1. 1. 1.]
fives = np.ones(5) * 5  # [5. 5. 5. 5. 5.]

# Sequential values
seq = np.arange(0, 11, 2)  # [0 2 4 6 8 10]  (start, stop, step)

# Evenly spaced values
linear = np.linspace(0, 1, 5)  # [0.  0.25  0.5  0.75  1.] (start, stop, count)

# Random values
random_vals = np.random.random(5)  # 5 random values between 0 and 1
random_ints = np.random.randint(0, 10, size=5)  # 5 random integers 0-9

# Identity matrix
I = np.eye(3)  # [[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]]

print("Zeros:", zeros)
print("Sequential:", seq)
print("Linear:", linear)
print("Identity:")
print(I)

### Array Attributes: Understanding Your Data

In [ ]:
import numpy as np
np.random.seed(0)  # for reproducibility

# Create arrays of different dimensions
x1 = np.random.randint(10, size=6)  # 1D array
x2 = np.random.randint(10, size=(3, 4))  # 2D array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3D array

print("x3 ndim: ", x3.ndim)  # 3
print("x3 shape:", x3.shape)  # (3, 4, 5)
print("x3 size: ", x3.size)  # 60

print("dtype:", x3.dtype)  # int64
print("itemsize:", x3.itemsize, "bytes")  # 8 bytes
print("nbytes:", x3.nbytes, "bytes")  # 480 bytes

> **Key Insight: Key Attributes**
> - **ndim**: number of dimensions
> - **shape**: size of each dimension
> - **size**: total number of elements
> - **dtype**: data type of elements

### Data Types in NumPy

| Common Data Types | Why It Matters |
|---|---|
| `int32`, `int64`: Integers | Memory: `float32` uses half the space |
| `float32`, `float64`: Floats | Precision: `float64` for high accuracy |
| `complex128`: Complex numbers | Speed: Smaller types = faster processing |
| `bool`: True/False | |

In [ ]:
# Specify dtype at creation
arr = np.array([1, 2, 3], dtype=np.float32)

# Convert dtype
arr_float64 = arr.astype(np.float64)

print(arr.dtype)        # float32
print(arr_float64.dtype)  # float64

In [ ]:
# Memory comparison
a32 = np.ones(1000000, dtype=np.float32)
a64 = np.ones(1000000, dtype=np.float64)

print(f"32-bit: {a32.nbytes/1e6} MB")
# 4.0 MB
print(f"64-bit: {a64.nbytes/1e6} MB")
# 8.0 MB

### Indexing and Slicing: Accessing Array Elements

In [ ]:
import numpy as np

# 1D array - similar to Python lists
x = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
print(x[0])      # 0 (first element)
print(x[-1])     # 9 (last element)
print(x[4:7])    # [4 5 6] (slice from index 4 to 6)
print(x[::2])    # [0 2 4 6 8] (every 2nd element)
print(x[::-1])   # [9 8 7 6 5 4 3 2 1 0] (reverse)

# 2D array - row, column indexing
x2 = np.array([[12, 5, 2, 4],
               [7, 6, 8, 8],
               [1, 6, 7, 7]])

print(x2[0, 0])    # 12 (element at row 0, col 0)
print(x2[2, -1])   # 7 (element at row 2, last column)
print(x2[0, :])    # [12  5  2  4] (first row)
print(x2[:, 1])    # [5 6 6] (second column)
print(x2[:2, :2])  # [[12  5], [ 7  6]] (2x2 subarray)

### [TOGETHER] Array Views vs Copies

In [ ]:
import numpy as np

# Original array
original = np.array([1, 2, 3, 4, 5])

# SLICING creates a VIEW (not a copy!)
view = original[1:4]
view[0] = 999
print(original)  # [1 999 3 4 5]  <-- Original changed!

# To create independent copy, use .copy()
original = np.array([1, 2, 3, 4, 5])
independent = original[1:4].copy()
independent[0] = 999
print(original)  # [1 2 3 4 5]  <-- Original unchanged
print(independent)  # [999 3 4]

> **Key Insight: Critical for Engineering!**
> Views save memory but can cause bugs. Always use `.copy()` when you need independent data.

### Reshaping Arrays

In [ ]:
import numpy as np

# 1D to 2D
loads = np.arange(12)
print(loads)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# Reshape to 3x4 matrix
matrix = loads.reshape(3, 4)
print(matrix)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Reshape to 4x3 matrix
matrix2 = loads.reshape(4, 3)
print(matrix2)
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

# Use -1 to auto-calculate one dimension
matrix3 = loads.reshape(2, -1)  # 2 rows, auto-calculate columns
print(matrix3.shape)  # (2, 6)

# Flatten back to 1D
flat = matrix.flatten()  # or .ravel() for view
print(flat)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

### Concatenating and Splitting Arrays

In [ ]:
import numpy as np

# Concatenate 1D arrays
dead_load = np.array([10, 15, 20])
live_load = np.array([5, 8, 10])
total_load = np.concatenate([dead_load, live_load])
print(total_load)  # [10 15 20  5  8 10]

# Stack vertically (vstack)
loads = np.vstack([dead_load, live_load])
print(loads)
# [[10 15 20]
#  [ 5  8 10]]

# Stack horizontally (hstack)
loads = np.hstack([dead_load, live_load])
print(loads)  # [10 15 20  5  8 10]

# Split array
split_loads = np.split(total_load, [3])  # Split at index 3
print(split_loads[0])  # [10 15 20]
print(split_loads[1])  # [ 5  8 10]

---
## 3. Array Operations and Universal Functions

### Vectorized Arithmetic: No Loops Needed!

In [ ]:
import numpy as np

# Create arrays
x = np.arange(4)
print("x =", x)  # [0 1 2 3]

# Element-wise operations (vectorized - FAST!)
print("x + 5 =", x + 5)    # [5 6 7 8]
print("x - 5 =", x - 5)    # [-5 -4 -3 -2]
print("x * 2 =", x * 2)    # [0 2 4 6]
print("x / 2 =", x / 2)    # [0.  0.5 1.  1.5]
print("x ** 2 =", x ** 2)  # [0 1 4 9]

# Multiple arrays
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print("a + b =", a + b)    # [5 5 5 5]
print("a * b =", a * b)    # [4 6 6 4]

# Compare to Python list (requires loop!)
# result = [x**2 for x in my_list]  # Slow!

### Universal Functions (ufuncs): Fast Operations

In [ ]:
import numpy as np

# Trigonometric functions
theta = np.linspace(0, np.pi, 3)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

# Exponential and logarithmic
x = [1, 2, 3]
print("e^x =", np.exp(x))       # [2.718  7.389  20.086]
print("2^x =", np.exp2(x))      # [2.  4.  8.]
print("log(x) =", np.log(x))    # [0.  0.693  1.099]

# Absolute value
x = np.array([-2, -1, 0, 1, 2])
print("abs(x) =", np.abs(x))    # [2 1 0 1 2]

# All much faster than Python loops!

### [EXPLORE] Example: Computation on Arrays

In [ ]:
import numpy as np

# Compute values of sin(x) for many values
x = np.linspace(0, np.pi, 3)
print("x      =", x)
# [0.         1.57079633 3.14159265]

print("sin(x) =", np.sin(x))
# [0.0000000e+00 1.0000000e+00 1.2246468e-16]

# Compute a more complex operation
x = np.arange(5)
y = np.empty(5)
for i in range(5):
    y[i] = x[i] ** 2
print(y)  # [ 0.  1.  4.  9. 16.]

# Much better with vectorization:
x = np.arange(5)
y = x ** 2
print(y)  # [ 0  1  4  9 16]

---
## 4. Aggregations and Statistics

### Basic Aggregations: Summarizing Data

In [ ]:
import numpy as np

# Random data
L = np.random.random(100)

# Summary statistics
print(np.sum(L))      # Sum of all values
print(np.min(L))      # Minimum value
print(np.max(L))      # Maximum value
print(np.mean(L))     # Mean
print(np.std(L))      # Standard deviation
print(np.var(L))      # Variance

# These also work as array methods:
print(L.sum())
print(L.min())
print(L.max())
print(L.mean())
print(L.std())

# Percentiles
print(np.percentile(L, 25))  # 1st quartile
print(np.median(L))          # 50th percentile
print(np.percentile(L, 75))  # 3rd quartile

### Multi-Dimensional Aggregations: The `axis` Parameter

In [ ]:
import numpy as np

# 2D array example
M = np.random.random((3, 4))
print(M)

# Aggregate along different axes
print("Shape:", M.shape)  # (3, 4)

# Sum all values
print(M.sum())

# Sum along axis 0 (collapse rows -> result has shape (4,))
print(M.sum(axis=0))

# Sum along axis 1 (collapse columns -> result has shape (3,))
print(M.sum(axis=1))

# Works with other functions too:
print(M.min(axis=0))  # Min of each column
print(M.max(axis=1))  # Max of each row

### More Aggregation Functions

In [ ]:
import numpy as np

data = np.array([10, 15, 20, 25, 30, 35, 40])

# Basic stats
print(f"Sum: {np.sum(data)}")         # 175
print(f"Product: {np.prod(data)}")    # 3.15e9
print(f"Mean: {np.mean(data)}")       # 25.0
print(f"Std: {np.std(data)}")         # 10.0
print(f"Variance: {np.var(data)}")    # 100.0

# Min/Max
print(f"Min: {np.min(data)}")         # 10
print(f"Max: {np.max(data)}")         # 40
print(f"Argmin: {np.argmin(data)}")   # 0 (index of min)
print(f"Argmax: {np.argmax(data)}")   # 6 (index of max)

# Cumulative operations
cumsum = np.cumsum(data)  # [10 25 45 70 100 135 175]
cumprod = np.cumprod(data[:4])  # [10 150 3000 75000]

# Boolean operations
print(f"Any > 50: {np.any(data > 50)}")    # False
print(f"All > 5: {np.all(data > 5)}")      # True

### [TOGETHER] Example: Analyzing Multi-Dimensional Data

In [ ]:
import numpy as np

# Precipitation data: 12 months x 5 years
precip_data = np.array([
    [3.2, 2.8, 3.5, 2.9, 3.1],  # January
    [2.5, 2.9, 2.3, 2.7, 2.6],  # February
    [3.8, 4.1, 3.6, 4.0, 3.9],  # March
    # ... (more months)
])

# Analysis
mean_per_month = np.mean(precip_data, axis=1)
mean_per_year = np.mean(precip_data, axis=0)
overall_mean = np.mean(precip_data)
overall_std = np.std(precip_data)

# Find extremes
max_precip = np.max(precip_data)
min_precip = np.min(precip_data)

print(f"Overall mean: {overall_mean:.2f}")
print(f"Std deviation: {overall_std:.2f}")
print(f"Range: {min_precip:.2f} - {max_precip:.2f}")

---
## 5. Broadcasting

### Broadcasting: Operating on Different Shapes

> **What is Broadcasting?**
> Broadcasting allows NumPy to perform operations on arrays of different shapes without explicitly replicating data.

> **Example: Broadcasting Rules**
> 1. If arrays have different dimensions, pad smaller shape with 1s on the left
> 2. If shapes don't match in a dimension, stretch dimension with size 1
> 3. If sizes disagree and neither is 1, raise error

> **Key Insight: Why It Matters**
> No loops needed! Operations are fast and memory-efficient. Essential for data science operations on large datasets.

### Broadcasting Examples

In [ ]:
import numpy as np

# Scalar + Array (broadcasts scalar to all elements)
a = np.array([0, 1, 2])
print(a + 5)  # array([5, 6, 7])

# 1D + 2D
a = np.ones((3, 3))
b = np.arange(3)
print(a + b)
# array([[1., 2., 3.],
#        [1., 2., 3.],
#        [1., 2., 3.]])

# Broadcasting with higher dimensions
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a + b)
# [[0 1 2]
#  [1 2 3]
#  [2 3 4]]

### Broadcasting in 2D: Centering Data

In [ ]:
import numpy as np

# Data matrix (10 observations x 3 features)
X = np.random.random((10, 3))

# Compute mean of each column (feature)
Xmean = X.mean(axis=0)

# Center the data (subtract mean from each column)
X_centered = X - Xmean

# Verify mean is now ~0 for each feature
print(X_centered.mean(axis=0))
# [~0. ~0. ~0.]

# This works because Xmean has shape (3,) which broadcasts
# to match X's shape (10, 3) by replicating across rows

### [EXPLORE] Broadcasting: Plotting Functions

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Create a 2D grid using broadcasting
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

# Broadcasting: x is (50,), y is (50,1)
# Result z is (50, 50)
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

plt.imshow(z, origin='lower', extent=[0, 5, 0, 5],
           cmap='viridis')
plt.colorbar()
plt.title('Broadcasting Example')
plt.show()

# This creates a 2D function from 1D arrays!

---
## 6. Boolean Operations and Masking

### Comparison Operators: Element-wise Comparisons

In [ ]:
import numpy as np

# Data array
x = np.array([1, 2, 3, 4, 5])

# Comparison operators return boolean arrays
print(x < 3)
# [ True  True False False False]

print(x > 3)
# [False False False  True  True]

print(x == 3)
# [False False  True False False]

# Multiple comparisons (use & and |, not 'and' and 'or')
print((x > 1) & (x < 5))
# [False  True  True  True False]

# Count how many satisfy condition
print(np.sum(x > 2))  # 3 (True=1, False=0)

# Percentage
print(np.mean(x > 2))  # 0.6 (60%)

### Boolean Indexing: Filtering Data

In [ ]:
import numpy as np

# Data array
x = np.array([1, 2, 3, 4, 5])

# Create boolean mask
mask = x < 3
print(mask)
# [ True  True False False False]

# Use mask to filter data
print(x[mask])  # [1 2]

# Can use directly without creating variable
print(x[x < 3])  # [1 2]

# More complex example with 2D
np.random.seed(0)
X = np.random.randint(10, size=(3, 4))
print(X)
# [[5 0 3 3]
#  [7 9 3 5]
#  [2 4 7 6]]

print(X[X < 5])  # [0 3 3 3 2 4] (flattened)

### Boolean Operators: Combining Conditions

In [ ]:
import numpy as np

# Example: Rainy days analysis
rainfall_inches = np.array([0.2, 0.5, 0.0, 1.2, 0.8, 0.0, 0.3])

# Multiple criteria with & (AND) and | (OR)
print((rainfall_inches > 0) & (rainfall_inches < 1))
# [ True  True False False  True False  True]

print((rainfall_inches <= 0) | (rainfall_inches >= 1))
# [False False  True  True False  True False]

# Use np.sum() to count matches
print(np.sum((rainfall_inches > 0) & (rainfall_inches < 1)))  # 4

# IMPORTANT: Use & and | for arrays, not 'and' and 'or'!
# Also: always use parentheses around conditions

# Boolean operators
print(~(rainfall_inches > 0.5))  # NOT
# [ True False  True False False  True  True]

### [TOGETHER] Example: Analyzing Weather Data

In [ ]:
import numpy as np

# Weather data
np.random.seed(1)
rainfall = np.random.random(365) * 2  # inches per day

# Analysis
rainy_days = np.sum(rainfall > 0.5)
dry_days = np.sum(rainfall < 0.1)
median_precip = np.median(rainfall)
mean_precip = np.mean(rainfall)

print(f"Rainy days (>0.5 in): {rainy_days}")
print(f"Dry days (<0.1 in): {dry_days}")
print(f"Median: {median_precip:.2f} in")
print(f"Mean: {mean_precip:.2f} in")

# Get all rainy day amounts
rainy = rainfall[rainfall > 0.5]
print(f"Average rainfall on rainy days: {rainy.mean():.2f} in")

---
## 7. Advanced Indexing

### Fancy Indexing: Using Arrays as Indices

In [ ]:
import numpy as np

# Simple array
x = np.array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

# Select specific elements by index
ind = [3, 7, 4]
print(x[ind])  # [71 86 60]

# 2D indexing
X = np.arange(12).reshape((3, 4))
print(X)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Select specific rows and columns
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[row, col])  # [ 2  5 11]

# Select a subset of rows
print(X[[0, 2]])
# [[ 0  1  2  3]
#  [ 8  9 10 11]]

### Modifying Values with Fancy Indexing

In [ ]:
import numpy as np

# Start with array of zeros
x = np.zeros(10)
print(x)  # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Set specific indices
ind = [0, 3, 5]
x[ind] = 99
print(x)  # [99.  0.  0. 99.  0. 99.  0.  0.  0.  0.]

# Increment specific values
x[ind] += 1
print(x)  # [100.   0.   0. 100.   0. 100.   0.   0.   0.   0.]

# Repeated indices - behavior is subtle!
x = np.zeros(5)
i = [0, 0, 0]
x[i] += 1
print(x)  # [1. 0. 0. 0. 0.] - only incremented once!

### Combined Indexing: Mix and Match

In [ ]:
import numpy as np

# 2D array
X = np.arange(12).reshape((3, 4))
print(X)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Fancy indexing + slicing
# Select rows 0 and 2, columns 1 and 3
result = X[[0, 2]][:, [1, 3]]
print(result)
# [[ 1  3]
#  [ 9 11]]

# Boolean mask + fancy indexing
mask = X[:, 1] > 5
print(mask)  # [False False  True]
print(X[mask])
# [[ 8  9 10 11]]

---
## 8. Sorting

### Sorting Arrays

In [ ]:
import numpy as np

# Unsorted array
x = np.array([2, 1, 4, 3, 5])

# Sort (returns new sorted array)
print(np.sort(x))  # [1 2 3 4 5]

# argsort: returns indices that would sort the array
i = np.argsort(x)
print(i)  # [1 0 3 2 4]
print(x[i])  # [1 2 3 4 5]

# Sort in descending order
print(x[np.argsort(x)[::-1]])  # [5 4 3 2 1]

# Sort 2D array along axis
np.random.seed(42)
X = np.random.randint(0, 10, (4, 6))
print(X)

# Sort each column
print(np.sort(X, axis=0))

# Sort each row
print(np.sort(X, axis=1))

### Practical Sorting: Finding Top N Elements

In [ ]:
import numpy as np

# Array of values
x = np.array([7, 2, 3, 1, 6, 5, 4])

# Partition: smallest 3 on left, rest on right
print(np.partition(x, 3))
# [2 1 3 4 6 5 7] (3 smallest values on left, not sorted)

# Get indices for partition
i = np.argpartition(x, 3)
print(x[i])
# [2 1 3 4 6 5 7]

# Find top K values efficiently
# Partition so K largest are on the right
K = 3
partitioned = np.partition(x, -K)
print(partitioned[-K:])  # [5 6 7] (not necessarily sorted)

# For sorted top K, use argsort
top_k_sorted = x[np.argsort(x)[-K:]]
print(top_k_sorted)  # [5 6 7]

---
## 9. Structured Data in NumPy

### Structured Arrays: Mixing Data Types

In [ ]:
import numpy as np

# Create structured array for person data
data = np.zeros(4, dtype={
    'names': ('name', 'age', 'weight'),
    'formats': ('U10', 'i4', 'f8')
})

# Fill data
data['name'] = ['Alice', 'Bob', 'Cathy', 'Doug']
data['age'] = [25, 45, 37, 19]
data['weight'] = [55.0, 85.5, 68.0, 61.5]

print(data)
# [('Alice', 25, 55. ) ('Bob', 45, 85.5)
#  ('Cathy', 37, 68. ) ('Doug', 19, 61.5)]

# Access by field name
print(data['name'])  # ['Alice' 'Bob' 'Cathy' 'Doug']
print(data['age'])   # [25 45 37 19]

# Filter
print(data[data['age'] < 30]['name'])  # ['Alice' 'Doug']

> **Key Insight: Note**
> For complex data, Pandas DataFrames are usually better! We cover Pandas in Week03b.

---
## Summary

This notebook covered the fundamental concepts of NumPy for numerical computing:

1. **Introduction to NumPy** - Understanding speed advantages and basic arrays
2. **Array Fundamentals** - Creating, indexing, reshaping, and combining arrays
3. **Array Operations** - Vectorized arithmetic and universal functions
4. **Aggregations** - Statistical operations and the axis parameter
5. **Broadcasting** - Operations on different array shapes
6. **Boolean Operations** - Masking and filtering data
7. **Advanced Indexing** - Fancy indexing for complex selections
8. **Sorting** - Organizing and finding top elements
9. **Structured Arrays** - Mixing data types (though Pandas is usually better)

### Key Takeaways:
- NumPy is 10-100x faster than Python lists for numerical operations
- Use vectorized operations instead of loops
- Broadcasting enables operations on different shapes without copying data
- Boolean masking is powerful for filtering data
- NumPy is the foundation for the entire PyData ecosystem

### NumPy Ecosystem: What's Built on Top

| Library | Purpose |
|---|---|
| **SciPy** | Scientific algorithms (optimization, integration, linear algebra) |
| **Pandas** | Structured data analysis (DataFrames) |
| **Matplotlib** | Visualization and plotting |
| **scikit-learn** | Machine learning |
| **TensorFlow/PyTorch** | Deep learning |

**Next**: Continue to Week03b for Pandas - Data Analysis for Engineers!